normalization-page-rob
Roman-Octavian/sys-dev-nosql-dbs pull request #10
Opened 2024-09-23 15:52 UTC by brrobert17

2024-09-23 17:55 UTC, Roman-Octavian approved these changes
Looks cool.

```css
max-width: 50vw;
```
I think the above breaks a bit (not too badly) with mobile viewports, but it's already too pretty for what it is so it doesn't matter.

Feel free to remove the HTML comment now that it's not needed, or not, it doesn't matter really.

2024-09-24 05:34 UTC, simonakardel commented on client/pages/normalization/styles.css
The style for the headings could go in the global css so we all have uniform styling

2024-09-24 16:00 UTC, Roman-Octavian requested changes

2024-09-24 16:00 UTC, Roman-Octavian commented on client/pages/er-diagrams/index.html
> +    <main class="erd-page">
The diff and git history is messed up in this PR.

Notice how it is including changes from Simona which you haven't really touched. And all her commits. The diff should always only display the changes that you have made, otherwise it is very hard to review a PR objectively, and it can cause issues in main too.

Want to try to fix it, or would you like me to try to fix it instead?

2024-09-24 16:08 UTC, brrobert17 commented
can you call me on discord and I can explain to you what I did and you can show me how to fix it?

2024-09-24 16:09 UTC, Roman-Octavian commented
> can you call me on discord and I can explain to you what I did and you can show me how to fix it?

VC 1

2024-09-24 16:22 UTC, Roman-Octavian approved these changes

2024-09-24 16:47 UTC, Roman-Octavian commented on client/styles.css
> +
Actually I just noticed but these rules are duplicated. Notice there is h1 h2 h3 above

2024-09-24 16:51 UTC, Roman-Octavian commented on client/styles.css
> +
I took the freedom to push the fix since I already pushed the force commit anyways so I might as well as save you time

2024-09-24 16:55 UTC, brrobert17 commented on client/styles.css
> +
well spotted. thank you!

2024-09-24 17:49 UTC, merged